/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.DoanhThuBUS;
import BUS.HoaDonBUS;
import Model.DOANHTHU;
import Model.HOADON;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author NK
 */
public class ChotCa extends javax.swing.JPanel {
    HOADON h = new HOADON();
    HoaDonBUS hoaDonBUS;
    DefaultTableModel defaultTableModel;
    float tongdt = 0;
    String testDate = "";
     String formattedDate;
     SimpleDateFormat dateFormat;
    /**
     * Creates new form ChotCa
     */
    public ChotCa() {
        initComponents();
        hoaDonBUS = new HoaDonBUS();        
        ArrayList<HOADON> hoadon = hoaDonBUS.selectAll(h);
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        String headerString[] = new String[]{"Mã hóa đơn", "Mã nhân viên", "Ngày hóa đơn", "Mã khách hàng", "Tổng hóa đơn"};
        defaultTableModel.setColumnIdentifiers(headerString);
        tableHoaDon1.setModel(defaultTableModel);
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jDateChooser1.addPropertyChangeListener("date", evt -> {
            Date selectedDate = jDateChooser1.getDate();
            if (selectedDate != null) {
                formattedDate = dateFormat.format(selectedDate);
                defaultTableModel.setRowCount(0); // clear existing rows
                setDataTable(hoadon, formattedDate);
            }
        });
        for (HOADON rec : hoadon){
            defaultTableModel.addRow(new Object[]{rec.getMaHD(),rec.getMaNV(),rec.getNgayHD(),rec.getMaKH(),rec.getTonghoadon()
            });
        }
        
        tableHoaDon1.setFocusable(false);
        jScrollPane1.setViewportView(tableHoaDon1);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
    
        tableHoaDon1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tableHoaDon1.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tableHoaDon1.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tableHoaDon1.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tableHoaDon1.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);  
        tableHoaDon1.setAutoCreateRowSorter(true);
        
    }
    private void setDataTable(ArrayList<HOADON> hoadon,String ngayhd) {
        for (HOADON rec : hoadon){
            String temp = rec.getNgayHD().toString();
            if(temp.equals(ngayhd)){
                tongdt += rec.getTonghoadon();
            defaultTableModel.addRow(new Object[]{rec.getMaHD(),rec.getMaNV(),rec.getNgayHD(),rec.getMaKH(),rec.getTonghoadon()
            });
        }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHoaDon1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        tableHoaDon1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableHoaDon1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 80));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(292, 80));

        jDateChooser1.setPreferredSize(new java.awt.Dimension(118, 24));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(408, 80));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calculator-tool.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 25, -1, -1));

        jButton2.setText("Chốt ca");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 25, -1, -1));

        jButton3.setText("Tính doanh thu");
        jButton3.setPreferredSize(new java.awt.Dimension(111, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 25, 130, -1));

        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("None");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, 239, 40));

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TinhDoanhThu doanhThu = new TinhDoanhThu();
        doanhThu.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int sodong = tableHoaDon1.getRowCount();
        if (sodong ==0||jLabel4.getText().equals("None")) {
            JOptionPane.showMessageDialog(null, " Không có thông tin để chốt ca ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
           
            DOANHTHU doanhthu = new DOANHTHU();
            LocalDate date = LocalDate.parse(formattedDate);
            doanhthu.setNgayLap(date);
            doanhthu.setTongDoanhThu(tongdt);
            DoanhThuBUS dtbus = new DoanhThuBUS();
            int er = dtbus.insert(doanhthu);
            if(er == 1 ){
                JOptionPane.showMessageDialog(null,"Ngày này đã được chốt ca","Lỗi",JOptionPane.ERROR_MESSAGE);
                return;
            }
             JOptionPane.showMessageDialog(null, " Chốt ca thành công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel4.setForeground(Color.black);
    
    // Lấy ngày từ JDateChooser
    Date selectedDate = jDateChooser1.getDate();
    
    if (selectedDate != null) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        formattedDate = dateFormat.format(selectedDate);
        
        if (formattedDate.equals(testDate)) {
            JOptionPane.showMessageDialog(null, "Ngày này đã được chọn", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            tongdt = 0;
            jLabel4.setText("");
            defaultTableModel.setRowCount(0);
            setDataTable(hoaDonBUS.selectAll(h), formattedDate);
            jLabel4.setText(String.valueOf(tongdt));
            testDate = formattedDate;
        }
    } else {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn một ngày hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableHoaDon1;
    // End of variables declaration//GEN-END:variables
}
