/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Bean.DanhMuc;
import Controller.ChuyenManHinh;
import java.awt.Color;
import java.util.ArrayList;
import  java.util.List;

/**
 *
 * @author NK
 */
public class Man_hinh_chinh extends javax.swing.JFrame {

    /**
     * Creates new form Man_hinh_chinh
     */
    public Man_hinh_chinh() {
        initComponents();
        setSize(1100, 670);
        // Đặt kích thước cố định cho JFrame
        setResizable(false);
        // Thiết lập hành động mặc định khi đóng cửa sổ
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        // Trung tâm JFrame trên màn hình
        setLocationRelativeTo(null);
        ChuyenManHinh controller = new ChuyenManHinh(jPaneView);
        controller.setView(jPanelTrangChu, jLabelTrangChu);
        List<DanhMuc> listItem= new ArrayList<>();
        listItem.add(new DanhMuc("TrangChu",jPanelTrangChu,jLabelTrangChu));
        listItem.add(new DanhMuc("HoaDon",HoaDonjpn,HoaDonjlb));
        listItem.add(new DanhMuc("SanPham",SanPhanjpn,SanPhamjlb));
        listItem.add(new DanhMuc("KhuyenMai",KhuyenMaijpn,KhuyenMaijlb));
        listItem.add(new DanhMuc("NhanVien",NhanVienjpn,NhanVienjlb));
        listItem.add(new DanhMuc("ChotCa",ChotCajpn,ChotCajlb));
        listItem.add(new DanhMuc("ThongKe",ThongKejpn,ThongKejlb));
        listItem.add(new DanhMuc("KhachHang",KhachHangjpn,KhachHangjlb));
        listItem.add(new DanhMuc("KhoHang",KhoHangjpn,KhoHangjlb));
        listItem.add(new DanhMuc("DangKi",Dangkijpn,Dangkijlb));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        LOGOHW = new javax.swing.JLabel();
        _______ = new javax.swing.JLabel();
        jPanelTrangChu = new javax.swing.JPanel();
        jLabelTrangChu = new javax.swing.JLabel();
        SanPhanjpn = new javax.swing.JPanel();
        SanPhamjlb = new javax.swing.JLabel();
        KhuyenMaijpn = new javax.swing.JPanel();
        KhuyenMaijlb = new javax.swing.JLabel();
        ThongKejpn = new javax.swing.JPanel();
        ThongKejlb = new javax.swing.JLabel();
        NhanVienjpn = new javax.swing.JPanel();
        NhanVienjlb = new javax.swing.JLabel();
        ChotCajpn = new javax.swing.JPanel();
        ChotCajlb = new javax.swing.JLabel();
        KhoHangjpn = new javax.swing.JPanel();
        KhoHangjlb = new javax.swing.JLabel();
        KhachHangjpn = new javax.swing.JPanel();
        KhachHangjlb = new javax.swing.JLabel();
        Dangkijpn = new javax.swing.JPanel();
        Dangkijlb = new javax.swing.JLabel();
        DangXuatjpn = new javax.swing.JPanel();
        DangXuatjlb = new javax.swing.JLabel();
        HoaDonjpn = new javax.swing.JPanel();
        HoaDonjlb = new javax.swing.JLabel();
        jPaneView = new javax.swing.JPanel();
        JLable_Exit = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/house (1).png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(null);

        jToggleButton1.setText("jToggleButton1");

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addGap(57, 57, 57))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));

        LOGOHW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/iconhw.png"))); // NOI18N
        LOGOHW.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        _______.setText("______________________________________________");

        jPanelTrangChu.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTrangChu.setBackground(new java.awt.Color(102, 255, 255));
        jLabelTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/house (1).png"))); // NOI18N
        jLabelTrangChu.setText("Trang Chủ");
        jLabelTrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicktrangchu(evt);
            }
        });

        javax.swing.GroupLayout jPanelTrangChuLayout = new javax.swing.GroupLayout(jPanelTrangChu);
        jPanelTrangChu.setLayout(jPanelTrangChuLayout);
        jPanelTrangChuLayout.setHorizontalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTrangChuLayout.setVerticalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrangChuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTrangChu)
                .addContainerGap())
        );

        SanPhanjpn.setBackground(new java.awt.Color(255, 255, 255));

        SanPhamjlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SanPhamjlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/goods.png"))); // NOI18N
        SanPhamjlb.setText("Sản Phẩm");
        SanPhamjlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout SanPhanjpnLayout = new javax.swing.GroupLayout(SanPhanjpn);
        SanPhanjpn.setLayout(SanPhanjpnLayout);
        SanPhanjpnLayout.setHorizontalGroup(
            SanPhanjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhanjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SanPhamjlb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        SanPhanjpnLayout.setVerticalGroup(
            SanPhanjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhanjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SanPhamjlb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        KhuyenMaijpn.setBackground(new java.awt.Color(255, 255, 255));

        KhuyenMaijlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        KhuyenMaijlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/discount-tag.png"))); // NOI18N
        KhuyenMaijlb.setText("Khuyến Mại");
        KhuyenMaijlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout KhuyenMaijpnLayout = new javax.swing.GroupLayout(KhuyenMaijpn);
        KhuyenMaijpn.setLayout(KhuyenMaijpnLayout);
        KhuyenMaijpnLayout.setHorizontalGroup(
            KhuyenMaijpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhuyenMaijpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KhuyenMaijlb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        KhuyenMaijpnLayout.setVerticalGroup(
            KhuyenMaijpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KhuyenMaijpnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KhuyenMaijlb)
                .addContainerGap())
        );

        ThongKejpn.setBackground(new java.awt.Color(255, 255, 255));

        ThongKejlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ThongKejlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/financial-statement (1).png"))); // NOI18N
        ThongKejlb.setText("Thống Kê");
        ThongKejlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout ThongKejpnLayout = new javax.swing.GroupLayout(ThongKejpn);
        ThongKejpn.setLayout(ThongKejpnLayout);
        ThongKejpnLayout.setHorizontalGroup(
            ThongKejpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKejpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThongKejlb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        ThongKejpnLayout.setVerticalGroup(
            ThongKejpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKejpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThongKejlb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NhanVienjpn.setBackground(new java.awt.Color(255, 255, 255));

        NhanVienjlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NhanVienjlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/employees.png"))); // NOI18N
        NhanVienjlb.setText("Nhân Viên");
        NhanVienjlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout NhanVienjpnLayout = new javax.swing.GroupLayout(NhanVienjpn);
        NhanVienjpn.setLayout(NhanVienjpnLayout);
        NhanVienjpnLayout.setHorizontalGroup(
            NhanVienjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NhanVienjlb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        NhanVienjpnLayout.setVerticalGroup(
            NhanVienjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhanVienjpnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NhanVienjlb)
                .addContainerGap())
        );

        ChotCajpn.setBackground(new java.awt.Color(255, 255, 255));

        ChotCajlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ChotCajlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/business-report.png"))); // NOI18N
        ChotCajlb.setText("Chốt Ca");
        ChotCajlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout ChotCajpnLayout = new javax.swing.GroupLayout(ChotCajpn);
        ChotCajpn.setLayout(ChotCajpnLayout);
        ChotCajpnLayout.setHorizontalGroup(
            ChotCajpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChotCajpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChotCajlb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        ChotCajpnLayout.setVerticalGroup(
            ChotCajpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChotCajpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChotCajlb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        KhoHangjpn.setBackground(new java.awt.Color(255, 255, 255));

        KhoHangjlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        KhoHangjlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/boxes.png"))); // NOI18N
        KhoHangjlb.setText("Kho Hàng");
        KhoHangjlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout KhoHangjpnLayout = new javax.swing.GroupLayout(KhoHangjpn);
        KhoHangjpn.setLayout(KhoHangjpnLayout);
        KhoHangjpnLayout.setHorizontalGroup(
            KhoHangjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhoHangjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KhoHangjlb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        KhoHangjpnLayout.setVerticalGroup(
            KhoHangjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhoHangjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KhoHangjlb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        KhachHangjpn.setBackground(new java.awt.Color(255, 255, 255));

        KhachHangjlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        KhachHangjlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/client.png"))); // NOI18N
        KhachHangjlb.setText("Khách Hàng");
        KhachHangjlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout KhachHangjpnLayout = new javax.swing.GroupLayout(KhachHangjpn);
        KhachHangjpn.setLayout(KhachHangjpnLayout);
        KhachHangjpnLayout.setHorizontalGroup(
            KhachHangjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachHangjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KhachHangjlb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        KhachHangjpnLayout.setVerticalGroup(
            KhachHangjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachHangjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KhachHangjlb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dangkijpn.setBackground(new java.awt.Color(255, 255, 255));

        Dangkijlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Dangkijlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/account.png"))); // NOI18N
        Dangkijlb.setText("Đăng Kí");
        Dangkijlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout DangkijpnLayout = new javax.swing.GroupLayout(Dangkijpn);
        Dangkijpn.setLayout(DangkijpnLayout);
        DangkijpnLayout.setHorizontalGroup(
            DangkijpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangkijpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dangkijlb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        DangkijpnLayout.setVerticalGroup(
            DangkijpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangkijpnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dangkijlb)
                .addContainerGap())
        );

        DangXuatjlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DangXuatjlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/logout.png"))); // NOI18N
        DangXuatjlb.setText("Đăng Xuất");
        DangXuatjlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DangXuatjlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatjlbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DangXuatjpnLayout = new javax.swing.GroupLayout(DangXuatjpn);
        DangXuatjpn.setLayout(DangXuatjpnLayout);
        DangXuatjpnLayout.setHorizontalGroup(
            DangXuatjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DangXuatjlb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        DangXuatjpnLayout.setVerticalGroup(
            DangXuatjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DangXuatjlb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HoaDonjpn.setBackground(new java.awt.Color(255, 255, 255));

        HoaDonjlb.setBackground(new java.awt.Color(204, 255, 204));
        HoaDonjlb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HoaDonjlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/bill.png"))); // NOI18N
        HoaDonjlb.setText("Hóa Đơn");
        HoaDonjlb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout HoaDonjpnLayout = new javax.swing.GroupLayout(HoaDonjpn);
        HoaDonjpn.setLayout(HoaDonjpnLayout);
        HoaDonjpnLayout.setHorizontalGroup(
            HoaDonjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HoaDonjpnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HoaDonjlb, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        HoaDonjpnLayout.setVerticalGroup(
            HoaDonjpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonjpnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HoaDonjlb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Dangkijpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LOGOHW, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_______, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SanPhanjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhuyenMaijpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThongKejpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NhanVienjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChotCajpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhoHangjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhachHangjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DangXuatjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoaDonjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOGOHW, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_______, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(HoaDonjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SanPhanjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KhuyenMaijpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NhanVienjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChotCajpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ThongKejpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KhachHangjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KhoHangjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Dangkijpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DangXuatjpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        JLable_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/close.png"))); // NOI18N
        JLable_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLable_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLable_Exitexit(evt);
            }
        });

        javax.swing.GroupLayout jPaneViewLayout = new javax.swing.GroupLayout(jPaneView);
        jPaneView.setLayout(jPaneViewLayout);
        jPaneViewLayout.setHorizontalGroup(
            jPaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneViewLayout.createSequentialGroup()
                .addContainerGap(800, Short.MAX_VALUE)
                .addComponent(JLable_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPaneViewLayout.setVerticalGroup(
            jPaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLable_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPaneView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void clicktrangchu(){}
    private void clicktrangchu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicktrangchu
        // TODO add your handling code here:
        setBackground(Color.yellow);
       
    }//GEN-LAST:event_clicktrangchu

    private void click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click
        // TODO add your handling code here:
        setBackground(Color.yellow);
    }//GEN-LAST:event_click

    private void JLable_Exitexit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLable_Exitexit
        System.exit(0);
    }//GEN-LAST:event_JLable_Exitexit

    private void DangXuatjlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatjlbMouseClicked
        // TODO add your handling code here:
        Login login= new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_DangXuatjlbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Man_hinh_chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Man_hinh_chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Man_hinh_chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Man_hinh_chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Man_hinh_chinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChotCajlb;
    private javax.swing.JPanel ChotCajpn;
    private javax.swing.JLabel DangXuatjlb;
    private javax.swing.JPanel DangXuatjpn;
    private javax.swing.JLabel Dangkijlb;
    private javax.swing.JPanel Dangkijpn;
    private javax.swing.JLabel HoaDonjlb;
    private javax.swing.JPanel HoaDonjpn;
    private javax.swing.JLabel JLable_Exit;
    private javax.swing.JLabel KhachHangjlb;
    private javax.swing.JPanel KhachHangjpn;
    private javax.swing.JLabel KhoHangjlb;
    private javax.swing.JPanel KhoHangjpn;
    private javax.swing.JLabel KhuyenMaijlb;
    private javax.swing.JPanel KhuyenMaijpn;
    private javax.swing.JLabel LOGOHW;
    private javax.swing.JLabel NhanVienjlb;
    private javax.swing.JPanel NhanVienjpn;
    private javax.swing.JLabel SanPhamjlb;
    private javax.swing.JPanel SanPhanjpn;
    private javax.swing.JLabel ThongKejlb;
    private javax.swing.JPanel ThongKejpn;
    private javax.swing.JLabel _______;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelTrangChu;
    private javax.swing.JPanel jPaneView;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelTrangChu;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
