/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.SanPhamBUS;
import Model.SANPHAM;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NK
 */
public class SanPham extends javax.swing.JPanel {
    SANPHAM s = new SANPHAM();
    SanPhamBUS sanPhamBUS;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form SanPham
     */
    public SanPham() {
        initComponents();
       tableSanPham2.fixTable(jScrollPane1);
       sanPhamBUS = new SanPhamBUS();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        tableSanPham2.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã sản phầm");
        defaultTableModel.addColumn("Tên sản phẩm");
        defaultTableModel.addColumn("Đơn vị tính");
        defaultTableModel.addColumn("Ngày sản xuất");
        defaultTableModel.addColumn("Hạn sử dụng");
        defaultTableModel.addColumn("Giá bán");
        defaultTableModel.addColumn("Giá nhập");
        defaultTableModel.addColumn("Số lượng tồn");
        
         setDataTable(sanPhamBUS.selectAll(s));
        
    }

    private void setDataTable(ArrayList<SANPHAM> spDao) {
        for (SANPHAM spSanpham : spDao){
            defaultTableModel.addRow(new Object[]{spSanpham.getMaSP(),spSanpham.getTenSP(),spSanpham.getDvt(),spSanpham.getNgaySX(),spSanpham.getHanSD(),spSanpham.getGiaBan(),
            spSanpham.getGiaNhap(),spSanpham.getSlSP()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanPham2 = new table.TableSanPham();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jScrollPane1.setViewportView(tableSanPham2);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextField1.setText("Nhập thông tin sản phẩm tìm kiếm");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicktimkiemsanpham(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/edit.png"))); // NOI18N
        jButton2.setText("Sửa");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/plus (2).png"))); // NOI18N
        jButton3.setText("Thêm");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanh_phan_log/icon/icon/bin.png"))); // NOI18N
        jButton4.setText("Xóa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clicktimkiemsanpham(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicktimkiemsanpham
        // TODO add your handling code here:
      jTextField1.setText("");
    }//GEN-LAST:event_clicktimkiemsanpham

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String valueText = jTextField1.getText();
        for(int i=0;i<tableSanPham2.getRowCount();i++){
            String masp = (String)tableSanPham2.getValueAt(i, 0);
            String tensp = (String)tableSanPham2.getValueAt(i, 1);
            if(masp.equalsIgnoreCase(valueText)||tensp.equalsIgnoreCase(valueText)){
                tableSanPham2.setRowSelectionInterval(i, i);
                tableSanPham2.scrollRectToVisible(tableSanPham2.getCellRect(i, 0, true));
                return;
            }
            
            tableSanPham2.clearSelection();}

    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private table.TableSanPham tableSanPham2;
    // End of variables declaration//GEN-END:variables
}
