/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.ChamCongBUS;
import BUS.NhanVienBUS;
import Model.CHAMCONG;
import Model.LUONGNHANVIEN;
import Model.NHANVIEN;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ADMIN
 */
public class TinhLuongNhanVien extends javax.swing.JFrame {
    CHAMCONG c = new CHAMCONG();
    NHANVIEN nv = new NHANVIEN();
    
    ChamCongBUS ccbus= new ChamCongBUS();
    NhanVienBUS nvbus = new NhanVienBUS();
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form TinhLuongNhanVien
     */
    public TinhLuongNhanVien() {
        initComponents();
        tableChamCong1.getColumnModel().getColumn(0).setPreferredWidth(210);
        tableChamCong1.getColumnModel().getColumn(1).setPreferredWidth(210);
        tableChamCong1.getColumnModel().getColumn(2).setPreferredWidth(210);
        tableChamCong1.getColumnModel().getColumn(3).setPreferredWidth(210);
         setLocationRelativeTo(null);
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        tableChamCong1.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã chấm công");
        defaultTableModel.addColumn("Mã nhân viên");
        defaultTableModel.addColumn("Ngày chấm công");
        defaultTableModel.addColumn("Số giờ làm");
        
        setDataTable(ccbus.selectAll(c));
    }

    public void setDataTable(ArrayList<CHAMCONG> ccDao) {
        defaultTableModel.setRowCount(0);
        for (CHAMCONG cc : ccDao){
            defaultTableModel.addRow(new Object[]{ cc.getMaCC(), cc.getMaNV(), cc.getNgayCC(), cc.getSoGioLam()
            });
        }
    }
    public void refreshTable(){
        defaultTableModel.setRowCount(0);
        setDataTable(ccbus.selectAll(c));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableChamCong1 = new table.TableChamCong();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMonthCbb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jYearCbb = new javax.swing.JComboBox<>();
        jLbSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        tableChamCong1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableChamCong1);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Nhập thông tin nhân viên");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calculator-tool.png"))); // NOI18N
        jButton1.setText("Tính lương ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tháng");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jMonthCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jMonthCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMonthCbbActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Năm");

        jYearCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "2021", "2022", "2023", "2024", "2025" }));

        jLbSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ic_Search.png"))); // NOI18N
        jLbSearch.setText("jLabel4");
        jLbSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMonthCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMonthCbb)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLbSearch)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(jYearCbb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<LUONGNHANVIEN> dsLuongNV = new ArrayList<>();
        String selectedMonth = jMonthCbb.getSelectedItem().toString();
        String selectedYear = jYearCbb.getSelectedItem().toString();
        
        if (selectedMonth.equals("--") || selectedYear.equals("--")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tháng và năm phù hợp để tính lương!");
        }
        else {
            for (int i = 0; i < defaultTableModel.getRowCount(); i++) {
                String maCC = defaultTableModel.getValueAt(i, 0).toString();
                String maNV = defaultTableModel.getValueAt(i, 1).toString();

                NHANVIEN nhanvien = nvbus.selectbyID(maNV);
                String tenNV = nhanvien.getTenNV();

                int soGioLam = Integer.parseInt(defaultTableModel.getValueAt(i, 3).toString());
                float luongcb = nhanvien.getLuong();
                float tongLuong = soGioLam * luongcb;

                dsLuongNV.add(new LUONGNHANVIEN(maCC, maNV, tenNV, tongLuong));
            }
            TongLuongNhanVien luongNV = new TongLuongNhanVien(dsLuongNV, selectedMonth, selectedYear);
            luongNV.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
      jTextField1.setText("");
      if(jTextField1.getText().isEmpty()){
          refreshTable();
      }
      jTextField1.setForeground(Color.black);
      TableRowSorter<DefaultTableModel> rowSorter;

         rowSorter = new TableRowSorter<>(defaultTableModel);
        tableChamCong1.setRowSorter(rowSorter);

        // Tạo JTextField để nhập từ khóa tìm kiếm
        
        jTextField1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String text = jTextField1.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
        });
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jMonthCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMonthCbbActionPerformed
        
    }//GEN-LAST:event_jMonthCbbActionPerformed

    private void jLbSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbSearchMouseClicked
        String selectedMonth = jMonthCbb.getSelectedItem().toString();
        String selectedYear = jYearCbb.getSelectedItem().toString();
        
        if (selectedMonth.equals("--") || selectedYear.equals("--")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tháng và năm phù hợp!");
        }
        else {
            // Clear the existing rows in the table
            defaultTableModel.setRowCount(0);

            // Get the attendance records for the selected month and year
            ArrayList<CHAMCONG> dsChamCong = ccbus.dsNhanVien(selectedMonth, selectedYear);

            // Update the table with the retrieved data
            for (CHAMCONG rec : dsChamCong) {
                defaultTableModel.addRow(new Object[]{rec.getMaCC(), rec.getMaNV(), rec.getNgayCC(), rec.getSoGioLam()});
            }
        }
    }//GEN-LAST:event_jLbSearchMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhLuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhLuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhLuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhLuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinhLuongNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbSearch;
    private javax.swing.JComboBox<String> jMonthCbb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jYearCbb;
    private table.TableChamCong tableChamCong1;
    // End of variables declaration//GEN-END:variables
}
