/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.DoanhThuBUS;
import BUS.DoanhThuThangBUS;
import BUS.HoaDonBUS;
import BUS.cthdBUS;
import Model.DOANHTHU;
import Model.DOANHTHUTHANG;
import Model.HOADON;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class TinhDoanhThu extends javax.swing.JFrame {
    DoanhThuBUS DoanhThuBUS;
    DefaultTableModel defaultTableModel;
    float tongdoanhthu = 0;
    DOANHTHU h = new DOANHTHU();
    float tongdtt = 0;
    /**
     * Creates new form TinhDoanhThu
     */
    public TinhDoanhThu() {
        initComponents();
        DoanhThuBUS = new DoanhThuBUS();        
        ArrayList<DOANHTHU> doanhthu = DoanhThuBUS.selectAll(h);
        defaultTableModel = new DefaultTableModel();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
         setLocationRelativeTo(null);
        String headerString[] = new String[]{"Ngày lập", "Tổng doanh thu"};
        defaultTableModel.setColumnIdentifiers(headerString);
        tableHoaDon1.setModel(defaultTableModel);
        for (DOANHTHU rec : doanhthu){
            defaultTableModel.addRow(new Object[]{rec.getNgayLap(),rec.getTongDoanhThu()
            });
        }
        
        tableHoaDon1.setFocusable(false);
        jScrollPane1.setViewportView(tableHoaDon1);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
    
        tableHoaDon1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tableHoaDon1.getColumnModel().getColumn(1).setCellRenderer(centerRenderer); 
        tableHoaDon1.setAutoCreateRowSorter(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHoaDon1 = new table.TableHoaDon();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableHoaDon1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tableHoaDon1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 1, 351, 490));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 83, 39));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calculator-tool.png"))); // NOI18N
        jButton1.setText("Tính Doanh Thu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, 39));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 83, 39));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("       Năm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 83, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("      Tháng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 83, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("None");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jLabel3.setPreferredSize(new java.awt.Dimension(142, 32));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, 39));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close_1.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jButton2.setText("Xuất Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    String nam = jComboBox1.getSelectedItem().toString();
    String thang = jComboBox2.getSelectedItem().toString();
    HoaDonBUS hoaDonBUS = new HoaDonBUS();
    DOANHTHU h = new DOANHTHU();
    ArrayList<DOANHTHU> doanhthu = DoanhThuBUS.selectAll(h);
    defaultTableModel.setRowCount(0);
    tongdtt = 0;
    for (DOANHTHU rec : doanhthu) {
        int monthenum = rec.getNgayLap().getMonthValue(); // Lấy tháng
        int yearenum = rec.getNgayLap().getYear(); // Lấy năm
        if (nam.equals(String.valueOf(yearenum)) && thang.equals(String.format("%02d", monthenum))) {
            tongdtt += rec.getTongDoanhThu();
            defaultTableModel.addRow(new Object[]{rec.getNgayLap(), rec.getTongDoanhThu()});
        }
    }
    jLabel3.setText(String.valueOf(tongdtt));
    String thangNam = thang + "-" + nam; // Format as MM/YYYY
    
    // Create a new DOANHTHUTHANG object and insert it into the database
    DOANHTHUTHANG doanhThuThang = new DOANHTHUTHANG(thangNam, tongdtt);
    DoanhThuThangBUS doanhThuThangBUS = new DoanhThuThangBUS();
    doanhThuThangBUS.insert(doanhThuThang);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
        // Create an instance of the Apache POI library classes
        org.apache.poi.ss.usermodel.Workbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook();
        org.apache.poi.ss.usermodel.Sheet sheet = workbook.createSheet("Doanh Thu Thang");

        // Create title row
        org.apache.poi.ss.usermodel.Row titleRow = sheet.createRow(0);
        org.apache.poi.ss.usermodel.Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue("BẢNG DOANH THU THEO THÁNG");

        // Merge title cells
        sheet.addMergedRegion(new org.apache.poi.ss.util.CellRangeAddress(0, 0, 0, 1));

        // Create header row
        org.apache.poi.ss.usermodel.Row headerRow = sheet.createRow(1);
        headerRow.createCell(0).setCellValue("Tháng");
        headerRow.createCell(1).setCellValue("Doanh thu của tháng");

        // Fetch data from the table
        ArrayList<DOANHTHUTHANG> doanhThuThangList = fetchDoanhThuThangData();
        int rowNum = 2;
        for (DOANHTHUTHANG record : doanhThuThangList) {
            org.apache.poi.ss.usermodel.Row row = sheet.createRow(rowNum++);
            row.createCell(0).setCellValue(record.getThangNam());
            row.createCell(1).setCellValue(record.getDtThang());
        }

        // Use JFileChooser to choose file save location
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Save As");
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            try (java.io.FileOutputStream fileOut = new java.io.FileOutputStream("DoanhThuThang.xlsx")) {
                workbook.write(fileOut);
            }
            workbook.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Xuất file Excel thành công!");
        }

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi xuất file Excel.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed
    
        private ArrayList<DOANHTHUTHANG> fetchDoanhThuThangData() {
        // Tạo một đối tượng DoanhThuThangBUS
        DoanhThuThangBUS doanhThuThangBUS = new DoanhThuThangBUS();
        // Tạo đối tượng DOANHTHUTHANG mặc định (hoặc có thể là null nếu phương thức hỗ trợ)
        DOANHTHUTHANG defaultFilter = new DOANHTHUTHANG();
        // Lấy tất cả dữ liệu từ bảng thông qua phương thức selectAll của DoanhThuThangBUS
        return doanhThuThangBUS.selectAll(defaultFilter);
    }
        
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private table.TableHoaDon tableHoaDon1;
    // End of variables declaration//GEN-END:variables
}
